routes/web.php
<?php

use App\Http\Controllers\ActivityController;
use App\Http\Controllers\AttachmentController;
use App\Http\Controllers\BudgetController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EarningController;
use App\Http\Controllers\IdeaController;
use App\Http\Controllers\ImportController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\RecurringController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ResendVerificationMailController;
use App\Http\Controllers\ResetPasswordController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\SpaceController;
use App\Http\Controllers\SpaceInviteController;
use App\Http\Controllers\SpendingController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\TranslationsController;
use App\Http\Controllers\VerifyController;

Route::get('/', [IndexController::class, 'index'])->name('index');

Route::group(['middleware' => ['guest']], function () {
    Route::get('/login', [LoginController::class, 'index'])->name('login');
    Route::post('/login', [LoginController::class, 'store']);

    Route::get('/verify/{token}', VerifyController::class)->name('verify');

    Route::get('/reset_password', [ResetPasswordController::class, 'get'])->name('reset_password');
    Route::post('/reset_password', [ResetPasswordController::class, 'post']);

    Route::get('/register', [RegisterController::class, 'index'])->name('register');
    Route::post('/register', [RegisterController::class, 'store']);
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');

    Route::post('/resend-verification-mail', ResendVerificationMailController::class)->name('resend_verification_mail');

    Route::post('/attachments', [AttachmentController::class, 'store']);
    Route::get('/attachments/{attachment}/download', [AttachmentController::class, 'download']);
    Route::post('/attachments/{id}/delete', [AttachmentController::class, 'delete']);

    Route::get('/transactions/create', [TransactionController::class, 'create'])->name('transactions.create');

    Route::name('transactions.')->group(function () {
        Route::get('/transactions', [TransactionController::class, 'index'])->name('index');
        Route::get('/transactions/create', [TransactionController::class, 'create'])->name('create');
    });

    Route::name('earnings.')->group(function () {
        Route::get('/earnings/{earning}', [EarningController::class, 'show'])->name('show');
        Route::get('/earnings/create', [EarningController::class, 'create'])->name('create');

        
        
        Route::post('/earnings', [EarningController::class, 'store']);



        Route::get('/earnings/{earning}/edit', [EarningController::class, 'edit'])->name('edit');
        Route::patch('/earnings/{earning}', [EarningController::class, 'update']);
        Route::delete('/earnings/{earning}', [EarningController::class, 'destroy']);
        Route::post('/earnings/{id}/restore', [EarningController::class, 'restore']);
    });

    Route::name('spendings.')->group(function () {
        Route::get('/spendings/{spending}', [SpendingController::class, 'show'])->name('show');
        Route::get('/spendings/create', [SpendingController::class, 'create'])->name('create');
        
        
        
        Route::post('/spendings', [SpendingController::class, 'store']);



        Route::get('/spendings/{spending}/edit', [SpendingController::class, 'edit'])->name('edit');
        Route::patch('/spendings/{spending}', [SpendingController::class, 'update']);
        Route::delete('/spendings/{spending}', [SpendingController::class, 'destroy']);
        Route::post('/spendings/{id}/restore', [SpendingController::class, 'restore']);
    });

    Route::resource('/recurrings', RecurringController::class)->only([
        'index',
        'create',
        'store',
        'show'
    ]);

    Route::resource('/budgets', BudgetController::class)->only([
        'index',
        'create',
        'store'
    ]);

    Route::resource('/tags', TagController::class)->only([
        'index',
        'create',
        'store',
        'edit',
        'update',
        'destroy'
    ]);

    Route::get('/reports', [ReportController::class, 'index'])->name('reports.index');
    Route::get('/reports/{slug}', [ReportController::class, 'show']);

    Route::name('imports.')->group(function () {
        Route::get('/imports', [ImportController::class, 'index'])->name('index');
        Route::get('/imports/create', [ImportController::class, 'create'])->name('create');
        Route::post('/imports', [ImportController::class, 'store'])->name('store');
        Route::get('/imports/{import}/prepare', [ImportController::class, 'getPrepare'])->name('prepare');
        Route::post('/imports/{import}/prepare', [ImportController::class, 'postPrepare']);
        Route::get('/imports/{import}/complete', [ImportController::class, 'getComplete'])->name('complete');
        Route::post('/imports/{import}/complete', [ImportController::class, 'postComplete']);
        Route::delete('/imports/{import}', [ImportController::class, 'destroy']);
    });

    Route::name('activities.')->group(function () {
        Route::get('/activities', [ActivityController::class, 'index'])->name('index');
    });

    Route::name('settings.')->group(function () {
        Route::get('/settings', [SettingsController::class, 'getIndex'])->name('index');
        Route::post('/settings', [SettingsController::class, 'postIndex']);
        Route::get('/settings/profile', [SettingsController::class, 'getProfile'])->name('profile');
        Route::get('/settings/account', [SettingsController::class, 'getAccount'])->name('account');
        Route::get('/settings/preferences', [SettingsController::class, 'getPreferences'])->name('preferences');
        Route::get('/settings/dashboard', [SettingsController::class, 'getDashboard'])->name('dashboard');
        Route::get('/settings/billing', [SettingsController::class, 'getBilling'])->name('billing')->middleware('stripe');
        Route::post('/settings/billing/upgrade', [SettingsController::class, 'postUpgrade'])->name('billing.upgrade')->middleware('stripe');
        Route::post('/settings/billing/cancel', [SettingsController::class, 'postCancel'])->name('billing.cancel')->middleware('stripe');
        Route::get('/settings/spaces', [SettingsController::class, 'getSpaces'])->name('spaces.index');
    });

    Route::name('spaces.')->group(function () {
        Route::get('/spaces/create', [SpaceController::class, 'create'])->name('create');
        Route::post('/spaces', [SpaceController::class, 'store'])->name('store');
        Route::get('/spaces/{space}', [SpaceController::class, 'show'])->name('show');
        Route::get('/spaces/{space}/edit', [SpaceController::class, 'edit'])->name('edit');
        Route::post('/spaces/{space}/update', [SpaceController::class, 'update'])->name('update');
        Route::post('/spaces/{space}/invite', [SpaceController::class, 'invite'])->name('invite');
    });

    Route::name('space_invites.')->group(function () {
        Route::get('/spaces/{space}/invites/{invite}', [SpaceInviteController::class, 'show'])->name('show');
        Route::post('/spaces/{space}/invites/{invite}/accept', [SpaceInviteController::class, 'accept'])->name('accept');
        Route::post('/spaces/{space}/invites/{invite}/deny', [SpaceInviteController::class, 'deny'])->name('deny');
    });

    Route::name('ideas.')->group(function () {
        Route::get('/ideas/create', [IdeaController::class, 'create'])->name('create');
        Route::post('/ideas', [IdeaController::class, 'store']);
    });

    Route::get('/translations', TranslationsController::class);
});

Route::get('/logout', [LogoutController::class, 'index'])->name('logout');

app/Models/Earning.php
<?php

namespace App\Models;

use App\Events\TransactionCreated;
use App\Events\TransactionDeleted;
use App\Helper;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Earning extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = [
        'space_id',
        'recurring_id',
        'happened_on',
        'description',
        'amount'
    ];

    protected $dispatchesEvents = [
        'created' => TransactionCreated::class,
        'deleted' => TransactionDeleted::class
    ];

    // Accessors
    public function getFormattedAmountAttribute()
    {
        return Helper::formatNumber($this->amount / 100);
    }

    public function getFormattedHappenedOnAttribute()
    {
        $secondsDifference = strtotime(date('Y-m-d')) - strtotime($this->happened_on);

        return ($secondsDifference / 60 / 60 / 24) . ' days ago';
    }

    // Relations
    public function attachments()
    {
        return $this->hasMany(Attachment::class, 'transaction_id')
            ->where('transaction_type', 'earning');
    }

    // Scopes
    public function scopeOfSpace($query, $spaceId)
    {
        return $query->where('space_id', $spaceId);
    }
}

app/Models/Recurring.php
<?php

namespace App\Models;

use App\Events\RecurringCreated;
use App\Events\RecurringDeleted;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Recurring extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'space_id',
        'type',
        'interval',
        'day',
        'starts_on',
        'ends_on',
        'last_used_on',
        'tag_id',
        'description',
        'amount',
        'currency_id'
    ];

    protected $dates = ['deleted_at'];

    protected $dispatchesEvents = [
        'created' => RecurringCreated::class,
        'deleted' => RecurringDeleted::class
    ];

    // Accessors
    public function getDueDaysAttribute()
    {
        if ($this->starts_on <= date('Y-m-d') && ($this->ends_on >= date('Y-m-d') || !$this->ends_on)) {
            if (date('j') > $this->day) {
                return date('t') - date('j') + $this->day;
            }

            return $this->day - date('j');
        }

        return 0;
    }

    public function getStatusAttribute()
    {
        return $this->starts_on <= date('Y-m-d') && ($this->ends_on >= date('Y-m-d') || !$this->ends_on);
    }

    // Relations
    public function space()
    {
        return $this->belongsTo(Space::class);
    }

    public function spendings()
    {
        return $this->hasMany(Spending::class);
    }

    public function tag()
    {
        return $this->belongsTo(Tag::class);
    }

    // Scopes
    public function scopeOfSpace($query, $spaceId)
    {
        return $query->where('space_id', $spaceId);
    }
}

app/Http/Controllers/RecurringController.php
<?php

namespace App\Http\Controllers;

use App\Helper;
use Illuminate\Http\Request;
use App\Models\Recurring;
use App\Jobs\ProcessRecurrings;
use App\Models\Tag;
use App\Repositories\RecurringRepository;

class RecurringController extends Controller
{
    private $recurringRepository;

    public function __construct(RecurringRepository $recurringRepository)
    {
        $this->recurringRepository = $recurringRepository;
    }

    public function index()
    {
        $recurrings = Recurring::ofSpace(session('space_id'))->latest()->get();

        return view('recurrings.index', ['recurrings' => $recurrings]);
    }

    public function show(Recurring $recurring)
    {
        $this->authorize('view', $recurring);

        return view('recurrings.show', compact('recurring'));
    }

    public function create()
    {
        $tags = [];

        foreach (Tag::ofSpace(session('space_id'))->get() as $tag) {
            $tags[] = ['key' => $tag->id, 'label' => $tag->name];
        }

        return view('recurrings.create', compact('tags'));
    }

    public function store(Request $request)
    {
        $request->validate($this->recurringRepository->getValidationRules());

        $recurring = $this->recurringRepository->create(
            session('space_id'),
            $request->type,
            $request->interval,
            (int) ltrim($request->input('day'), 0),
            $request->start,
            $request->input('end', null),
            $request->input('tag', null),
            $request->input('description'),
            Helper::rawNumberToInteger($request->input('amount')),
            $request->currency_id
        );

        ProcessRecurrings::dispatch();

        return redirect()->route('recurrings.show', ['recurring' => $recurring->id]);
    }
}

resources/views/recurrings/create.blade.php
@extends('layout')

@section('title', __('actions.create') . ' ' . __('models.recurring'))

@section('body')
    <div class="wrapper mw-400 my-3">
        <h2 class="mb-3">{{ __('actions.create') }} {{ __('models.recurring') }}</h2>
        <form method="POST" action="/recurrings" autocomplete="off">
            {{ csrf_field() }}
            <div class="input input--small">
                <label>Day</label>
                <input type="text" name="day" />
                <div style="font-weight: 700; font-size: 14px; margin-top: 5px;">1 - 28</div>
                @include('partials.validation_error', ['payload' => 'day'])
            </div>
            <div class="input input--small">
                <label>End</label>
                <DatePicker name="end"></DatePicker>
                @include('partials.validation_error', ['payload' => 'end'])
                <input type="checkbox" name="end" value="" id="endForever" />
                <label for="endForever">Forever</label>
            </div>
            <div class="input input--small">
                <label>Tag</label>
                <searchable
                    name="tag"
                    :items='@json($tags)'
                    initial="{{ old('tag') }}"></searchable>
                @include('partials.validation_error', ['payload' => 'tag'])
            </div>
            <div class="input input--small">
                <label>Description</label>
                <input type="text" name="description" />
                @include('partials.validation_error', ['payload' => 'description'])
            </div>
            <div class="input input--small">
                <label>Amount</label>
                <input type="text" name="amount" />
                @include('partials.validation_error', ['payload' => 'amount'])
            </div>
            <div class="row row--right">
                <div class="row__column row__column--compact">
                    <button class="button">{{ __('actions.create') }}</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/recurrings/index.blade.php
@extends('layout')

@section('title', __('models.recurrings'))

@section('body')
    <div class="wrapper my-3">
        <div class="row mb-3">
            <div class="row__column row__column--middle">
                <h2>{{ __('models.recurrings') }}</h2>
            </div>
            <div class="row__column row__column--compact row__column--middle">
                <a href="/recurrings/create" class="button">{{ __('actions.create') }} {{ __('models.recurring') }}</a>
            </div>
        </div>
        <div class="box mt-3">
            @if (count($recurrings))
                @foreach ($recurrings as $recurring)
                    <div class="box__section row">
                        <div class="row__column">
                            <div class="color-dark">
                                <a href="/recurrings/{{ $recurring->id }}" v-pre>{{ $recurring->description }}</a>
                            </div>
                            <div class="row mt-1">
                                <div class="row__column row__column--compact" style="font-size: 14px; font-weight: 600;">{!! $currency !!} {{ \App\Helper::formatNumber($recurring->amount / 100) }}</div>
                                @if ($recurring->due_days)
                                    <div class="row__column row__column--compact ml-2" style="font-size: 14px; font-weight: 600;"><i class="fas fa-clock"></i> Due in {{ $recurring->due_days }} days</div>
                                @endif
                            </div>
                        </div>
                        <div class="row__column row__column--middle">
                            @if ($recurring->status)
                                <span style="border-radius: 5px; background: #D8F9E8; color: #51B07F; padding: 5px 10px; font-size: 14px; font-weight: 600;"><i class="fas fa-check fa-xs"></i> Active</span>
                            @else
                                <span style="border-radius: 5px; background: #FFE7EC; color: #F25C68; padding: 5px 10px; font-size: 14px; font-weight: 600;"><i class="fas fa-times fa-xs"></i> Inactive</span>
                            @endif
                        </div>
                        <div class="row__column row__column--middle">
                            @if ($recurring->tag)
                                @include('partials.tag', ['payload' => $recurring->tag])
                            @endif
                        </div>
                    </div>
                @endforeach
            @else
                @include('partials.empty_state', ['payload' => 'recurrings'])
            @endif
        </div>
    </div>
@endsection

resources/views/recurrings/show.blade.php
@extends('layout')

@section('body')
    <div class="wrapper my-3">
        <h2 v-pre>{{ $recurring->description }}</h2>
        <div class="row my-3">
            <div class="row__column row__column--compact">
                @if ($recurring->status)
                    <span style="border-radius: 5px; background: #D8F9E8; color: #51B07F; padding: 5px 10px; font-size: 14px; font-weight: 600;"><i class="fas fa-check fa-xs"></i> Active</span>
                @else
                    <span style="border-radius: 5px; background: #FFE7EC; color: #F25C68; padding: 5px 10px; font-size: 14px; font-weight: 600;"><i class="fas fa-times fa-xs"></i> Inactive</span>
                @endif
            </div>
            @if ($recurring->tag)
                <div class="row__column row__column--compact ml-1">
                    @include('partials.tag', ['payload' => $recurring->tag])
                </div>
            @endif
        </div>
        <div class="color-dark mb-2">{{ __('models.spendings') }}</div>
        <div class="box">
            @if (count($recurring->spendings))
                @foreach ($recurring->spendings as $spending)
                    <div class="box__section">
                        <div>
                            <div class="color-dark">{{ $spending->happened_on }}</div>
                            <div class="mt-1" style="font-size: 14px; font-weight: 600;">{{ $spending->formatted_happened_on }}</div>
                        </div>
                        <div></div>
                    </div>
                @endforeach
            @else
                <div class="box__section text-center">There aren't any spendings (yet)</div>
            @endif
        </div>
    </div>
@endsection