routes/web.php
<?php

use App\Http\Controllers\ActivityController;
use App\Http\Controllers\AttachmentController;
use App\Http\Controllers\BudgetController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EarningController;
use App\Http\Controllers\IdeaController;
use App\Http\Controllers\ImportController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\RecurringController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ResendVerificationMailController;
use App\Http\Controllers\ResetPasswordController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\SpaceController;
use App\Http\Controllers\SpaceInviteController;
use App\Http\Controllers\SpendingController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\TranslationsController;
use App\Http\Controllers\VerifyController;

Route::get('/', [IndexController::class, 'index'])->name('index');

Route::group(['middleware' => ['guest']], function () {
    Route::get('/login', [LoginController::class, 'index'])->name('login');
    Route::post('/login', [LoginController::class, 'store']);

    Route::get('/verify/{token}', VerifyController::class)->name('verify');

    Route::get('/reset_password', [ResetPasswordController::class, 'get'])->name('reset_password');
    Route::post('/reset_password', [ResetPasswordController::class, 'post']);

    Route::get('/register', [RegisterController::class, 'index'])->name('register');
    Route::post('/register', [RegisterController::class, 'store']);
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');

    Route::post('/resend-verification-mail', ResendVerificationMailController::class)->name('resend_verification_mail');

    Route::post('/attachments', [AttachmentController::class, 'store']);
    Route::get('/attachments/{attachment}/download', [AttachmentController::class, 'download']);
    Route::post('/attachments/{id}/delete', [AttachmentController::class, 'delete']);

    Route::get('/transactions/create', [TransactionController::class, 'create'])->name('transactions.create');

    Route::name('transactions.')->group(function () {
        Route::get('/transactions', [TransactionController::class, 'index'])->name('index');
        Route::get('/transactions/create', [TransactionController::class, 'create'])->name('create');
    });

    Route::name('earnings.')->group(function () {
        Route::get('/earnings/{earning}', [EarningController::class, 'show'])->name('show');
        Route::get('/earnings/create', [EarningController::class, 'create'])->name('create');

        
        
        Route::post('/earnings', [EarningController::class, 'store']);



        Route::get('/earnings/{earning}/edit', [EarningController::class, 'edit'])->name('edit');
        Route::patch('/earnings/{earning}', [EarningController::class, 'update']);
        Route::delete('/earnings/{earning}', [EarningController::class, 'destroy']);
        Route::post('/earnings/{id}/restore', [EarningController::class, 'restore']);
    });

    Route::name('spendings.')->group(function () {
        Route::get('/spendings/{spending}', [SpendingController::class, 'show'])->name('show');
        Route::get('/spendings/create', [SpendingController::class, 'create'])->name('create');
        
        
        
        Route::post('/spendings', [SpendingController::class, 'store']);



        Route::get('/spendings/{spending}/edit', [SpendingController::class, 'edit'])->name('edit');
        Route::patch('/spendings/{spending}', [SpendingController::class, 'update']);
        Route::delete('/spendings/{spending}', [SpendingController::class, 'destroy']);
        Route::post('/spendings/{id}/restore', [SpendingController::class, 'restore']);
    });

    Route::resource('/recurrings', RecurringController::class)->only([
        'index',
        'create',
        'store',
        'show'
    ]);

    Route::resource('/budgets', BudgetController::class)->only([
        'index',
        'create',
        'store'
    ]);

    Route::resource('/tags', TagController::class)->only([
        'index',
        'create',
        'store',
        'edit',
        'update',
        'destroy'
    ]);

    Route::get('/reports', [ReportController::class, 'index'])->name('reports.index');
    Route::get('/reports/{slug}', [ReportController::class, 'show']);

    Route::name('imports.')->group(function () {
        Route::get('/imports', [ImportController::class, 'index'])->name('index');
        Route::get('/imports/create', [ImportController::class, 'create'])->name('create');
        Route::post('/imports', [ImportController::class, 'store'])->name('store');
        Route::get('/imports/{import}/prepare', [ImportController::class, 'getPrepare'])->name('prepare');
        Route::post('/imports/{import}/prepare', [ImportController::class, 'postPrepare']);
        Route::get('/imports/{import}/complete', [ImportController::class, 'getComplete'])->name('complete');
        Route::post('/imports/{import}/complete', [ImportController::class, 'postComplete']);
        Route::delete('/imports/{import}', [ImportController::class, 'destroy']);
    });

    Route::name('activities.')->group(function () {
        Route::get('/activities', [ActivityController::class, 'index'])->name('index');
    });

    Route::name('settings.')->group(function () {
        Route::get('/settings', [SettingsController::class, 'getIndex'])->name('index');
        Route::post('/settings', [SettingsController::class, 'postIndex']);
        Route::get('/settings/profile', [SettingsController::class, 'getProfile'])->name('profile');
        Route::get('/settings/account', [SettingsController::class, 'getAccount'])->name('account');
        Route::get('/settings/preferences', [SettingsController::class, 'getPreferences'])->name('preferences');
        Route::get('/settings/dashboard', [SettingsController::class, 'getDashboard'])->name('dashboard');
        Route::get('/settings/billing', [SettingsController::class, 'getBilling'])->name('billing')->middleware('stripe');
        Route::post('/settings/billing/upgrade', [SettingsController::class, 'postUpgrade'])->name('billing.upgrade')->middleware('stripe');
        Route::post('/settings/billing/cancel', [SettingsController::class, 'postCancel'])->name('billing.cancel')->middleware('stripe');
        Route::get('/settings/spaces', [SettingsController::class, 'getSpaces'])->name('spaces.index');
    });

    Route::name('spaces.')->group(function () {
        Route::get('/spaces/create', [SpaceController::class, 'create'])->name('create');
        Route::post('/spaces', [SpaceController::class, 'store'])->name('store');
        Route::get('/spaces/{space}', [SpaceController::class, 'show'])->name('show');
        Route::get('/spaces/{space}/edit', [SpaceController::class, 'edit'])->name('edit');
        Route::post('/spaces/{space}/update', [SpaceController::class, 'update'])->name('update');
        Route::post('/spaces/{space}/invite', [SpaceController::class, 'invite'])->name('invite');
    });

    Route::name('space_invites.')->group(function () {
        Route::get('/spaces/{space}/invites/{invite}', [SpaceInviteController::class, 'show'])->name('show');
        Route::post('/spaces/{space}/invites/{invite}/accept', [SpaceInviteController::class, 'accept'])->name('accept');
        Route::post('/spaces/{space}/invites/{invite}/deny', [SpaceInviteController::class, 'deny'])->name('deny');
    });

    Route::name('ideas.')->group(function () {
        Route::get('/ideas/create', [IdeaController::class, 'create'])->name('create');
        Route::post('/ideas', [IdeaController::class, 'store']);
    });

    Route::get('/translations', TranslationsController::class);
});

Route::get('/logout', [LogoutController::class, 'index'])->name('logout');

app/Models/Recurring.php
<?php

namespace App\Models;

use App\Events\RecurringCreated;
use App\Events\RecurringDeleted;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Recurring extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'space_id',
        'type',
        'interval',
        'day',
        'starts_on',
        'ends_on',
        'last_used_on',
        'tag_id',
        'description',
        'amount',
        'currency_id'
    ];

    protected $dates = ['deleted_at'];

    protected $dispatchesEvents = [
        'created' => RecurringCreated::class,
        'deleted' => RecurringDeleted::class
    ];

    // Accessors
    public function getDueDaysAttribute()
    {
        if ($this->starts_on <= date('Y-m-d') && ($this->ends_on >= date('Y-m-d') || !$this->ends_on)) {
            if (date('j') > $this->day) {
                return date('t') - date('j') + $this->day;
            }

            return $this->day - date('j');
        }

        return 0;
    }

    public function getStatusAttribute()
    {
        return $this->starts_on <= date('Y-m-d') && ($this->ends_on >= date('Y-m-d') || !$this->ends_on);
    }

    // Relations
    public function space()
    {
        return $this->belongsTo(Space::class);
    }

    public function spendings()
    {
        return $this->hasMany(Spending::class);
    }

    public function tag()
    {
        return $this->belongsTo(Tag::class);
    }

    // Scopes
    public function scopeOfSpace($query, $spaceId)
    {
        return $query->where('space_id', $spaceId);
    }
}

app/Models/Space.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class Space extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'currency_id',
        'name'
    ];

    protected $dates = ['deleted_at'];

    // Relations
    public function users()
    {
        return $this->belongsToMany(User::class, 'user_space')->withPivot('role');
    }

    public function invites()
    {
        return $this->hasMany(SpaceInvite::class);
    }

    public function currency()
    {
        return $this->belongsTo(Currency::class);
    }

    public function tags()
    {
        return $this->hasMany(Tag::class);
    }

    public function earnings()
    {
        return $this->hasMany(Earning::class);
    }

    public function spendings()
    {
        return $this->hasMany(Spending::class);
    }

    public function recurrings()
    {
        return $this->hasMany(Recurring::class);
    }

    public function imports()
    {
        return $this->hasMany(Import::class);
    }

    public function activities()
    {
        return $this->hasMany(Activity::class);
    }

    // Accessors
    public function getAbbreviatedNameAttribute(): string
    {
        return Str::limit($this->name, 3);
    }

    //
    public function monthlyBalance($year, $month)
    {
        $earningsAmount = Earning::where('space_id', $this->id)
            ->whereYear('happened_on', $year)
            ->whereMonth('happened_on', $month)
            ->sum('amount');

        $spendingsAmount = Spending::where('space_id', $this->id)
            ->whereYear('happened_on', $year)
            ->whereMonth('happened_on', $month)
            ->sum('amount');

        if (!$spendingsAmount) {
            return $earningsAmount;
        } else {
            return $earningsAmount - $spendingsAmount;
        }
    }

    public function monthlyRecurrings($year, $month)
    {
        $query = DB::selectOne('
            SELECT SUM(amount) as amount
            FROM recurrings
            WHERE space_id = :space_id
                AND YEAR(starts_on) <= :start_year
                AND MONTH(starts_on) <= :start_month
                AND ((YEAR(ends_on) >= :end_year AND MONTH(ends_on) >= :end_month) OR ends_on IS NULL)
        ', [
            'space_id' => $this->id,
            'start_year' => $year,
            'start_month' => $month,
            'end_year' => $year,
            'end_month' => $month
        ]);

        return $query->amount;
    }
}

app/Http/Controllers/SpaceController.php
<?php

namespace App\Http\Controllers;

use App\Actions\CreateSpaceAction;
use App\Actions\CreateSpaceInviteAction;
use App\Actions\StoreSpaceInSessionAction;
use App\Exceptions\SpaceInviteAlreadyExistsException;
use App\Exceptions\SpaceInviteInviteeAlreadyPresentException;
use App\Mail\InvitedToSpace;
use App\Models\Currency;
use App\Models\Space;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;

class SpaceController extends Controller
{
    public function create()
    {
        $currencies = Currency::all();

        return view('spaces.create', ['currencies' => $currencies]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:255',
            'currency_id' => 'required|exists:currencies,id'
        ]);

        if (!$request->user()->can('create', Space::class)) {
            $request->session()->flash('maximum_reached', true);

            return redirect()->route('spaces.create');
        }

        (new CreateSpaceAction())->execute($request->name, $request->currency_id, Auth::id());

        return redirect()->route('settings.spaces.index');
    }

    public function show($id)
    {
        $space = Space::find($id);

        if ($space->users->contains(Auth::user()->id)) {
            (new StoreSpaceInSessionAction())->execute($space->id);
        }

        return redirect()->route('dashboard');
    }

    public function edit(Space $space)
    {
        if (Auth::user()->cant('edit', $space)) {
            return redirect()->route('settings.spaces.index');
        }

        return view('spaces.edit', ['space' => $space]);
    }

    public function update(Request $request, Space $space)
    {
        if (Auth::user()->cant('edit', $space)) {
            return redirect()->route('settings.spaces.index');
        }

        $request->validate([
            'name' => 'required|max:255'
        ]);

        $space->fill([
            'name' => $request->name
        ])->save();

        return redirect()->route('settings.spaces.index');
    }

    public function invite(Request $request, Space $space)
    {
        $authenticatedUser = Auth::user();

        if ($authenticatedUser->cant('edit', $space)) {
            return redirect()->route('settings.spaces.index');
        }

        $request->validate([
            'email' => 'required|exists:users,email',
            'role' => 'required|in:admin,regular'
        ]);

        $inviteeUser = User::where('email', $request->email)->first();

        try {
            $invite = (new CreateSpaceInviteAction())->execute(
                $space->id,
                $inviteeUser->id,
                $authenticatedUser->id,
                $request->role
            );
        } catch (SpaceInviteInviteeAlreadyPresentException $e) {
            return redirect()
                ->route('spaces.edit', ['space' => $space->id])
                ->with('inviteStatus', 'present');
        } catch (SpaceInviteAlreadyExistsException $e) {
            return redirect()
                ->route('spaces.edit', ['space' => $space->id])
                ->with('inviteStatus', 'exists');
        }

        Mail::to($inviteeUser->email)->send(new InvitedToSpace($invite));

        return redirect()
            ->route('spaces.edit', ['space' => $space->id])
            ->with('inviteStatus', 'success');
    }
}

resources/views/spaces/create.blade.php
@extends('layout')

@section('title', __('actions.create') . ' ' . __('models.space'))

@section('body')
    <div class="wrapper my-3">
        <h2 class="mb-3">{{ __('actions.create') }} {{ __('models.space') }}</h2>
        @if (Session::get('maximum_reached') === true)
            <div class="mt-3 c-red" style="line-height: 150%;">You have reached the maximum amount of spaces you can be part of.</div>
        @endif
        <div class="box mt-3">
            <form method="POST" action="{{ route('spaces.store') }}" autocomplete="off">
                {{ csrf_field() }}
                <div class="box__section">
                    <div class="input input--small">
                        <label>{{ __('fields.name') }}</label>
                        <input type="text" name="name" />
                        @include('partials.validation_error', ['payload' => 'name'])
                    </div>
                    <div class="input input--small mb-0">
                        <label>{{ __('fields.currency') }}</label>
                        <select name="currency_id">
                            @foreach ($currencies as $currency)
                                <option value="{{ $currency->id }}">{{ $currency->name }}</option>
                            @endforeach
                        </select>
                        @include('partials.validation_error', ['payload' => 'currency_id'])
                    </div>
                </div>
                <div class="box__section box__section--highlight row row--right">
                    <div class="row__column row__column--compact row__column--middle">
                        <a href="{{ route('settings.spaces.index') }}">{{ __('actions.cancel') }}</a>
                    </div>
                    <div class="row__column row__column--compact ml-2">
                        <button class="button">{{ __('actions.create') }}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/spaces/edit.blade.php
@extends('layout')

@section('title', __('actions.edit') . ' ' . __('models.space'))

@section('body')
    <div class="wrapper my-3">
        <h2 class="mb-3">{{ __('actions.edit') }} {{ __('models.space') }}</h2>
        <form method="POST" action="/spaces/{{ $space->id }}/update">
            {{ csrf_field() }}
            <div class="box">
                <div class="box__section row">
                    <div class="row__column">
                        <h2>{{ __('general.general') }}</h2>
                    </div>
                    <div class="row__column row__column--double">
                        <div class="input input--small">
                            <label>{{ __('fields.name') }}</label>
                            <input type="text" name="name" value="{{ $space->name }}" />
                        </div>
                        <div class="input input--small mb-0">
                            <label>{{ __('fields.currency') }}</label>
                            <select disabled>
                                <option>{{ $space->currency->name }}</option>
                            </select>
                            <div class="hint mt-05">You cannot modify the currency anymore</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row row--right mt-2">
                <a class="button button--secondary mr-2" href="/settings/spaces">{{ __('actions.cancel') }}</a>
                <button class="button">{{ __('actions.save') }}</button>
            </div>
        </form>
        <div class="box mt-3">
            <div class="box__section row">
                <div class="row__column">
                    <h2>{{ __('general.members') }}</h2>
                </div>
                <div class="row__column row__column--double">
                    @foreach ($space->users as $i => $user)
                        <div class="{{ $i > 0 ? 'mt-2' : null }}">
                            <div class="color-dark mb-1" v-pre>{{ $user->name }}</div>
                            <div class="fs-sm">{{ ucfirst($user->pivot->role) }}</div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
        <div class="box mt-3">
            <div class="box__section row">
                <div class="row__column">
                    <h2>{{ __('general.invites') }}</h2>
                </div>
                <div class="row__column row__column--double">
                    @if (!count($space->invites))
                        <span>There aren't any invites</span>
                    @endif
                    @foreach ($space->invites as $i => $invite)
                        <div class="{{ $i > 0 ? 'mt-2' : '' }}">
                            <div class="color-dark mb-1" v-pre>{{ $invite->invitee->name }}</div>
                            <div class="fs-sm" v-pre>{{ __('general.invited_by') }} {{ $invite->inviter->name }} &middot; {{ $invite->status }}</div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
        <div class="box mt-3">
            <div class="box__section row">
                <div class="row__column">
                    <h2>{{ __('general.invite_someone') }}</h2>
                </div>
                <div class="row__column row__column--double">
                    @if (session('inviteStatus'))
                        @switch(session('inviteStatus'))
                            @case('success')
                                <div class="color-green mb-2">An invite has been sent</div>
                                @break

                            @case('present')
                                <div class="color-red mb-2">User is already part of space</div>
                                @break

                            @case('exists')
                                <div class="color-red mb-2">Invite has already been sent</div>
                                @break
                        @endswitch
                    @endif
                    <form method="POST" action="/spaces/{{ $space->id }}/invite">
                        {{ csrf_field() }}
                        <div class="input input--small">
                            <label>{{ __('fields.email') }}</label>
                            <input type="email" name="email" />
                            @include('partials.validation_error', ['payload' => 'email'])
                        </div>
                        <div class="input input--small">
                            <label>{{ __('fields.role') }}</label>
                            <select name="role">
                                <option value="admin">Admin</option>
                                <option value="regular" selected>Regular</option>
                            </select>
                            @include('partials.validation_error', ['payload' => 'role'])
                        </div>
                        <button class="button">{{ __('actions.invite') }}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection