routes/web.php
<?php

use App\Http\Controllers\ActivityController;
use App\Http\Controllers\AttachmentController;
use App\Http\Controllers\BudgetController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EarningController;
use App\Http\Controllers\IdeaController;
use App\Http\Controllers\ImportController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\RecurringController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ResendVerificationMailController;
use App\Http\Controllers\ResetPasswordController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\SpaceController;
use App\Http\Controllers\SpaceInviteController;
use App\Http\Controllers\SpendingController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\TranslationsController;
use App\Http\Controllers\VerifyController;

Route::get('/', [IndexController::class, 'index'])->name('index');

Route::group(['middleware' => ['guest']], function () {
    Route::get('/login', [LoginController::class, 'index'])->name('login');
    Route::post('/login', [LoginController::class, 'store']);

    Route::get('/verify/{token}', VerifyController::class)->name('verify');

    Route::get('/reset_password', [ResetPasswordController::class, 'get'])->name('reset_password');
    Route::post('/reset_password', [ResetPasswordController::class, 'post']);

    Route::get('/register', [RegisterController::class, 'index'])->name('register');
    Route::post('/register', [RegisterController::class, 'store']);
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');

    Route::post('/resend-verification-mail', ResendVerificationMailController::class)->name('resend_verification_mail');

    Route::post('/attachments', [AttachmentController::class, 'store']);
    Route::get('/attachments/{attachment}/download', [AttachmentController::class, 'download']);
    Route::post('/attachments/{id}/delete', [AttachmentController::class, 'delete']);

    Route::get('/transactions/create', [TransactionController::class, 'create'])->name('transactions.create');

    Route::name('transactions.')->group(function () {
        Route::get('/transactions', [TransactionController::class, 'index'])->name('index');
        Route::get('/transactions/create', [TransactionController::class, 'create'])->name('create');
    });

    Route::name('earnings.')->group(function () {
        Route::get('/earnings/{earning}', [EarningController::class, 'show'])->name('show');
        Route::get('/earnings/create', [EarningController::class, 'create'])->name('create');

        
        
        Route::post('/earnings', [EarningController::class, 'store']);



        Route::get('/earnings/{earning}/edit', [EarningController::class, 'edit'])->name('edit');
        Route::patch('/earnings/{earning}', [EarningController::class, 'update']);
        Route::delete('/earnings/{earning}', [EarningController::class, 'destroy']);
        Route::post('/earnings/{id}/restore', [EarningController::class, 'restore']);
    });

    Route::name('spendings.')->group(function () {
        Route::get('/spendings/{spending}', [SpendingController::class, 'show'])->name('show');
        Route::get('/spendings/create', [SpendingController::class, 'create'])->name('create');
        
        
        
        Route::post('/spendings', [SpendingController::class, 'store']);



        Route::get('/spendings/{spending}/edit', [SpendingController::class, 'edit'])->name('edit');
        Route::patch('/spendings/{spending}', [SpendingController::class, 'update']);
        Route::delete('/spendings/{spending}', [SpendingController::class, 'destroy']);
        Route::post('/spendings/{id}/restore', [SpendingController::class, 'restore']);
    });

    Route::resource('/recurrings', RecurringController::class)->only([
        'index',
        'create',
        'store',
        'show'
    ]);

    Route::resource('/budgets', BudgetController::class)->only([
        'index',
        'create',
        'store'
    ]);

    Route::resource('/tags', TagController::class)->only([
        'index',
        'create',
        'store',
        'edit',
        'update',
        'destroy'
    ]);

    Route::get('/reports', [ReportController::class, 'index'])->name('reports.index');
    Route::get('/reports/{slug}', [ReportController::class, 'show']);

    Route::name('imports.')->group(function () {
        Route::get('/imports', [ImportController::class, 'index'])->name('index');
        Route::get('/imports/create', [ImportController::class, 'create'])->name('create');
        Route::post('/imports', [ImportController::class, 'store'])->name('store');
        Route::get('/imports/{import}/prepare', [ImportController::class, 'getPrepare'])->name('prepare');
        Route::post('/imports/{import}/prepare', [ImportController::class, 'postPrepare']);
        Route::get('/imports/{import}/complete', [ImportController::class, 'getComplete'])->name('complete');
        Route::post('/imports/{import}/complete', [ImportController::class, 'postComplete']);
        Route::delete('/imports/{import}', [ImportController::class, 'destroy']);
    });

    Route::name('activities.')->group(function () {
        Route::get('/activities', [ActivityController::class, 'index'])->name('index');
    });

    Route::name('settings.')->group(function () {
        Route::get('/settings', [SettingsController::class, 'getIndex'])->name('index');
        Route::post('/settings', [SettingsController::class, 'postIndex']);
        Route::get('/settings/profile', [SettingsController::class, 'getProfile'])->name('profile');
        Route::get('/settings/account', [SettingsController::class, 'getAccount'])->name('account');
        Route::get('/settings/preferences', [SettingsController::class, 'getPreferences'])->name('preferences');
        Route::get('/settings/dashboard', [SettingsController::class, 'getDashboard'])->name('dashboard');
        Route::get('/settings/billing', [SettingsController::class, 'getBilling'])->name('billing')->middleware('stripe');
        Route::post('/settings/billing/upgrade', [SettingsController::class, 'postUpgrade'])->name('billing.upgrade')->middleware('stripe');
        Route::post('/settings/billing/cancel', [SettingsController::class, 'postCancel'])->name('billing.cancel')->middleware('stripe');
        Route::get('/settings/spaces', [SettingsController::class, 'getSpaces'])->name('spaces.index');
    });

    Route::name('spaces.')->group(function () {
        Route::get('/spaces/create', [SpaceController::class, 'create'])->name('create');
        Route::post('/spaces', [SpaceController::class, 'store'])->name('store');
        Route::get('/spaces/{space}', [SpaceController::class, 'show'])->name('show');
        Route::get('/spaces/{space}/edit', [SpaceController::class, 'edit'])->name('edit');
        Route::post('/spaces/{space}/update', [SpaceController::class, 'update'])->name('update');
        Route::post('/spaces/{space}/invite', [SpaceController::class, 'invite'])->name('invite');
    });

    Route::name('space_invites.')->group(function () {
        Route::get('/spaces/{space}/invites/{invite}', [SpaceInviteController::class, 'show'])->name('show');
        Route::post('/spaces/{space}/invites/{invite}/accept', [SpaceInviteController::class, 'accept'])->name('accept');
        Route::post('/spaces/{space}/invites/{invite}/deny', [SpaceInviteController::class, 'deny'])->name('deny');
    });

    Route::name('ideas.')->group(function () {
        Route::get('/ideas/create', [IdeaController::class, 'create'])->name('create');
        Route::post('/ideas', [IdeaController::class, 'store']);
    });

    Route::get('/translations', TranslationsController::class);
});

Route::get('/logout', [LogoutController::class, 'index'])->name('logout');

app/Http/Controllers/SettingsController.php
<?php

namespace App\Http\Controllers;

use App\Actions\CreateStripeCheckoutAction;
use App\Actions\CreateStripeCustomerAction;
use App\Actions\FetchStripeSubscriptionAction;
use App\Exceptions\UserStripelessException;
use Illuminate\Http\Request;
use App\Mail\PasswordChanged;
use Auth;
use Image;
use Storage;
use Hash;
use Mail;

class SettingsController extends Controller
{
    public function getIndex()
    {
        return redirect()->route('settings.profile');
    }

    public function postIndex(Request $request)
    {
        $request->validate([
            'avatar' => 'nullable|mimes:jpeg,jpg,png,gif',
            'password' => 'nullable|confirmed',
            'language' => 'nullable|in:' . implode(',', array_keys(config('app.locales'))),
            'theme' => 'nullable|in:light,dark',
            'weekly_report' => 'nullable|in:true,false',
            'default_transaction_type' => 'nullable|in:earning,spending',
            'first_day_of_week' => 'nullable|in:sunday,monday'
        ]);

        $user = Auth::user();

        // Profile
        if ($request->hasFile('avatar')) {
            $file = $request->file('avatar');

            $fileName = $file->hashName();

            $image = Image::make($file)
                ->fit(500);

            Storage::put('public/avatars/' . $fileName, (string) $image->encode());

            $user->avatar = $fileName;
        }

        if ($request->has('name')) {
            $user->name = $request->input('name');
        }

        // Account
        if ($request->has('email')) {
            $user->email = $request->input('email');
        }

        if ($password = $request->input('password')) {
            $user->password = Hash::make($password);
        }

        // Preferences
        if ($request->has('language')) {
            $user->language = $request->input('language');
        }

        if ($request->has('theme')) {
            $user->theme = $request->input('theme');
        }

        if ($request->has('weekly_report')) {
            $user->weekly_report = $request->input('weekly_report') == 'true' ? true : false;
        }

        if ($request->has('default_transaction_type')) {
            $user->default_transaction_type = $request->input('default_transaction_type');
        }

        if ($request->has('first_day_of_week')) {
            $user->first_day_of_week = $request->input('first_day_of_week');
        }

        $user->save();

        // Notify upon changing of password
        if ($request->has('password')) {
            Mail::to($user->email)->queue(new PasswordChanged($user->updated_at));
        }

        return back();
    }

    public function getProfile()
    {
        return view('settings.profile');
    }

    public function getAccount()
    {
        return view('settings.account');
    }

    public function getSpaces()
    {
        return view('settings.spaces.index', [
            'spaces' => Auth::user()->spaces
        ]);
    }

    public function getPreferences()
    {
        $languages = [];

        foreach (config('app.locales') as $key => $value) {
            $flag = $key;

            if ($key == 'en') {
                $flag = 'us';
            }

            $languages[] = ['key' => $key, 'label' => '<i class="twf twf-s twf-' . $flag . '"></i> ' . $value];
        }

        return view('settings.preferences', compact('languages'));
    }

    public function getDashboard()
    {
        return view('settings.dashboard');
    }

    public function getBilling(Request $request)
    {
        $user = $request->user();
        $stripeSubscription = null;

        try {
            $stripeSubscription = (new FetchStripeSubscriptionAction())->execute($user->id);
        } catch (UserStripelessException $e) {
            // Don't worry, $stripeSubscription will simply be `null`
        }

        return view('settings.billing', [
            'user' => $user,
            'stripeSubscription' => $stripeSubscription
        ]);
    }

    public function postUpgrade(Request $request)
    {
        $user = $request->user();

        if (!$user->stripe_customer_id) {
            (new CreateStripeCustomerAction())->execute($user->id);
        }

        $stripeSubscription = (new FetchStripeSubscriptionAction())->execute($user->id);

        if ($stripeSubscription) {
            return redirect()->route('settings.billing');
        }

        $stripeCheckoutId = (new CreateStripeCheckoutAction())->execute($user->id);

        return view('stripe_checkout_redirect', ['stripeCheckoutId' => $stripeCheckoutId]);
    }

    public function postCancel(Request $request)
    {
        $user = $request->user();

        if (!$user->stripe_customer_id) {
            return redirect()->route('settings.billing');
        }

        $stripeSubscription = (new FetchStripeSubscriptionAction())->execute($user->id);

        if (!$stripeSubscription) {
            return redirect()->route('settings.billing');
        }

        $stripeSubscription->cancel();

        return redirect()->route('settings.billing');
    }
}

resources/views/settings/account.blade.php
@extends('settings.layout')

@section('settings_title')
    <h2 class="mb-3">{{ __('general.account') }}</h2>
@endsection

@section('settings_body')
    <div class="box">
        <div class="box__section">
            <div class="input input--small">
                <label>{{ __('fields.email') }}</label>
                <input type="email" name="email" value="{{ Auth::user()->email }}" />
            </div>
            <div class="row">
                <div class="row__column input">
                    <label>{{ __('fields.password') }}</label>
                    <input type="password" name="password" />
                    @include('partials.validation_error', ['payload' => 'password'])
                </div>
                <div class="row__column input ml-2">
                    <label>{{ __('actions.verify') }} {{ __('fields.password') }}</label>
                    <input type="password" name="password_confirmation" />
                    @include('partials.validation_error', ['payload' => 'password_confirmation'])
                </div>
            </div>
            <button class="button">{{ __('actions.save') }}</button>
        </div>
    </div>
@endsection

resources/views/settings/billing.blade.php
@extends('settings.layout')

@section('settings_title')
    <h2 class="mb-3">{{ __('general.billing') }}</h2>
@endsection

@section('settings_body_formless')
    <div class="box">
        <div class="box__section">
            <div class="row row--middle mb-1">
                <div style="color: black;" class="mr-1">{{ $stripeSubscription ? 'Premium' : 'Standard' }}</div>
                @if (!$stripeSubscription)
                    <form method="POST" action="{{ route('settings.billing.upgrade') }}">
                        {{ csrf_field() }}
                        <button class="button button--small">Upgrade</button>
                    </form>
                @else
                    <form method="POST" action="{{ route('settings.billing.cancel') }}">
                        {{ csrf_field() }}
                        <button class="button button--small button--secondary">Cancel</button>
                    </form>
                @endif
            </div>
            € {{ $stripeSubscription ? \App\Helper::formatNumber($stripeSubscription->plan->amount / 100) : '0.00' }} per month @if ($stripeSubscription)&middot; Next payment due on {{ date('Y-m-d', $stripeSubscription->current_period_end) }}@endif
        </div>
    </div>
@endsection

resources/views/settings/dashboard.blade.php
@extends('settings.layout')

@section('settings_title')
    <h2 class="mb-3">{{ __('general.dashboard') }}</h2>
@endsection

@section('settings_body_formless')
    <div class="mb-2">
        <livewire:widget-wizard />
    </div>
    <livewire:widget-list />
@endsection

resources/views/settings/layout.blade.php
@extends('layout')

@section('body')
    <div class="wrapper my-3">
        <div class="row row--responsive">
            <div class="row__column mr-3" style="max-width: 300px;">
                <div class="box">
                    <div class="box__section box__section--header">{{ __('pages.settings') }}</div>
                    <ul class="box__section">
                        <li><a href="/settings/profile"><i class="fas fa-user fa-sm"></i> {{ __('general.profile') }}</a></li>
                        <li><a href="/settings/account"><i class="fas fa-lock fa-sm"></i> {{ __('general.account') }}</a></li>
                        <li><a href="/settings/preferences"><i class="fas fa-sliders-h fa-sm"></i> {{ __('general.preferences') }}</a></li>
                        <li><a href="/settings/dashboard"><i class="fas fa-home fa-sm"></i> {{ __('general.dashboard') }}</a></li>
                        @if ($arePlansEnabled)
                            <li><a href="/settings/billing"><i class="fas fa-wallet fa-sm"></i> {{ __('general.billing') }}</a></li>
                        @endif
                        <li><a href="/settings/spaces"><i class="fas fa-rocket fa-sm"></i> {{ __('models.spaces') }}</a></li>
                    </ul>
                </div>
            </div>
            <div class="row__column">
                @yield('settings_title')
                <form method="POST" action="/settings" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    @yield('settings_body')
                </form>
                @yield('settings_body_formless')
            </div>
        </div>
    </div>
@endsection

resources/views/settings/preferences.blade.php
@extends('settings.layout')

@section('settings_title')
    <h2 class="mb-3">{{ __('general.preferences') }}</h2>
@endsection

@section('settings_body')
    <div class="box">
        <div class="box__section">
            <div class="input input--small">
                <label>{{ __('fields.language') }}</label>
                <searchable
                    name="language"
                    :items='@json($languages)'
                    initial="{{ Auth::user()->language }}"></searchable>
                @include('partials.validation_error', ['payload' => 'language'])
            </div>
            <div class="input input--small">
                <label>{{ __('fields.theme') }}</label>
                <select name="theme">
                    <option value="light" {{ Auth::user()->theme == 'light' ? 'selected' : '' }}>Light</option>
                    <option value="dark" {{ Auth::user()->theme == 'dark' ? 'selected' : '' }}>Dark (Experimental)</option>
                </select>
                @include('partials.validation_error', ['payload' => 'theme'])
            </div>
            <div class="input input--small">
                <label>{{ __('fields.weekly_report') }}</label>
                <div>
                    <input type="radio" name="weekly_report" value="true" {{ Auth::user()->weekly_report ? 'checked' : '' }} /> {{ __('actions.yes') }}
                </div>
                <div>
                    <input type="radio" name="weekly_report" value="false" {{ Auth::user()->weekly_report ? '' : 'checked' }} /> {{ __('actions.no') }}
                </div>
                @include('partials.validation_error', ['payload' => 'weekly_report'])
            </div>
            <div class="input input--small">
                <label>{{ __('fields.default_transaction_type') }}</label>
                <div>
                    <input type="radio" name="default_transaction_type" value="earning" {{ Auth::user()->default_transaction_type === 'earning' ? 'checked' : '' }} /> {{ __('models.earning') }}
                </div>
                <div>
                    <input type="radio" name="default_transaction_type" value="spending" {{ Auth::user()->default_transaction_type === 'spending' ? 'checked' : '' }} /> {{ __('models.spending') }}
                </div>
                @include('partials.validation_error', ['payload' => 'default_transaction_type'])
            </div>
            <div class="input input--small">
                <label>{{ __('fields.first_day_of_week') }}</label>
                <div>
                    <input type="radio" name="first_day_of_week" value="sunday" {{ Auth::user()->first_day_of_week === 'sunday' ? 'checked' : '' }} /> {{ __('calendar.weekdays.6') }}
                </div>
                <div>
                    <input type="radio" name="first_day_of_week" value="monday" {{ Auth::user()->first_day_of_week === 'monday' ? 'checked' : '' }} /> {{ __('calendar.weekdays.0') }}
                </div>
                @include('partials.validation_error', ['payload' => 'first_day_of_week'])
            </div>
            <button class="button">{{ __('actions.save') }}</button>
        </div>
    </div>
@endsection

resources/views/settings/profile.blade.php
@extends('settings.layout')

@section('settings_title')
    <h2 class="mb-3">{{ __('general.profile') }}</h2>
@endsection

@section('settings_body')
    <div class="box">
        <div class="box__section">
            <div class="input input--small">
                <label>{{ __('fields.avatar') }}</label>
                <img src="{{ Auth::user()->avatar }}" style="width: 200px; height: 200px; border-radius: 5px; object-fit: cover;" />
                <input type="file" name="avatar" />
                @include('partials.validation_error', ['payload' => 'avatar'])
            </div>
            <div class="input input--small">
                <label>@lang('fields.name')</label>
                <input type="text" name="name" value="{{ Auth::user()->name }}" />
            </div>
            <button class="button">{{ __('actions.save') }}</button>
        </div>
    </div>
@endsection